/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PublicPrayerTimesRouteImport } from './routes/_public.prayer-times'
import { Route as PublicMonthlyTimetableRouteImport } from './routes/_public.monthly-timetable'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicAnnouncementsRouteImport } from './routes/_public.announcements'
import { Route as AdminAdministratorIndexRouteImport } from './routes/_admin.administrator.index'
import { Route as AdminAdministratorPrayerTimesRouteImport } from './routes/_admin.administrator.prayer-times'
import { Route as AdminAdministratorEventsRouteImport } from './routes/_admin.administrator.events'
import { Route as AdminAdministratorAnnouncementsRouteImport } from './routes/_admin.administrator.announcements'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPrayerTimesRoute = PublicPrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMonthlyTimetableRoute = PublicMonthlyTimetableRouteImport.update({
  id: '/monthly-timetable',
  path: '/monthly-timetable',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAnnouncementsRoute = PublicAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdministratorIndexRoute = AdminAdministratorIndexRouteImport.update({
  id: '/administrator/',
  path: '/administrator/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorPrayerTimesRoute =
  AdminAdministratorPrayerTimesRouteImport.update({
    id: '/administrator/prayer-times',
    path: '/administrator/prayer-times',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministratorEventsRoute =
  AdminAdministratorEventsRouteImport.update({
    id: '/administrator/events',
    path: '/administrator/events',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdministratorAnnouncementsRoute =
  AdminAdministratorAnnouncementsRouteImport.update({
    id: '/administrator/announcements',
    path: '/administrator/announcements',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/announcements': typeof PublicAnnouncementsRoute
  '/events': typeof PublicEventsRoute
  '/monthly-timetable': typeof PublicMonthlyTimetableRoute
  '/prayer-times': typeof PublicPrayerTimesRoute
  '/admin/login': typeof AdminLoginRoute
  '/administrator/announcements': typeof AdminAdministratorAnnouncementsRoute
  '/administrator/events': typeof AdminAdministratorEventsRoute
  '/administrator/prayer-times': typeof AdminAdministratorPrayerTimesRoute
  '/administrator/': typeof AdminAdministratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/announcements': typeof PublicAnnouncementsRoute
  '/events': typeof PublicEventsRoute
  '/monthly-timetable': typeof PublicMonthlyTimetableRoute
  '/prayer-times': typeof PublicPrayerTimesRoute
  '/admin/login': typeof AdminLoginRoute
  '/administrator/announcements': typeof AdminAdministratorAnnouncementsRoute
  '/administrator/events': typeof AdminAdministratorEventsRoute
  '/administrator/prayer-times': typeof AdminAdministratorPrayerTimesRoute
  '/administrator': typeof AdminAdministratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/announcements': typeof PublicAnnouncementsRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/monthly-timetable': typeof PublicMonthlyTimetableRoute
  '/_public/prayer-times': typeof PublicPrayerTimesRoute
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/administrator/announcements': typeof AdminAdministratorAnnouncementsRoute
  '/_admin/administrator/events': typeof AdminAdministratorEventsRoute
  '/_admin/administrator/prayer-times': typeof AdminAdministratorPrayerTimesRoute
  '/_admin/administrator/': typeof AdminAdministratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/events'
    | '/monthly-timetable'
    | '/prayer-times'
    | '/admin/login'
    | '/administrator/announcements'
    | '/administrator/events'
    | '/administrator/prayer-times'
    | '/administrator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/events'
    | '/monthly-timetable'
    | '/prayer-times'
    | '/admin/login'
    | '/administrator/announcements'
    | '/administrator/events'
    | '/administrator/prayer-times'
    | '/administrator'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/_public/announcements'
    | '/_public/events'
    | '/_public/monthly-timetable'
    | '/_public/prayer-times'
    | '/admin/login'
    | '/_public/'
    | '/_admin/administrator/announcements'
    | '/_admin/administrator/events'
    | '/_admin/administrator/prayer-times'
    | '/_admin/administrator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/prayer-times': {
      id: '/_public/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PublicPrayerTimesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/monthly-timetable': {
      id: '/_public/monthly-timetable'
      path: '/monthly-timetable'
      fullPath: '/monthly-timetable'
      preLoaderRoute: typeof PublicMonthlyTimetableRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/announcements': {
      id: '/_public/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof PublicAnnouncementsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/administrator/': {
      id: '/_admin/administrator/'
      path: '/administrator'
      fullPath: '/administrator/'
      preLoaderRoute: typeof AdminAdministratorIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/administrator/prayer-times': {
      id: '/_admin/administrator/prayer-times'
      path: '/administrator/prayer-times'
      fullPath: '/administrator/prayer-times'
      preLoaderRoute: typeof AdminAdministratorPrayerTimesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/administrator/events': {
      id: '/_admin/administrator/events'
      path: '/administrator/events'
      fullPath: '/administrator/events'
      preLoaderRoute: typeof AdminAdministratorEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/administrator/announcements': {
      id: '/_admin/administrator/announcements'
      path: '/administrator/announcements'
      fullPath: '/administrator/announcements'
      preLoaderRoute: typeof AdminAdministratorAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdministratorAnnouncementsRoute: typeof AdminAdministratorAnnouncementsRoute
  AdminAdministratorEventsRoute: typeof AdminAdministratorEventsRoute
  AdminAdministratorPrayerTimesRoute: typeof AdminAdministratorPrayerTimesRoute
  AdminAdministratorIndexRoute: typeof AdminAdministratorIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministratorAnnouncementsRoute: AdminAdministratorAnnouncementsRoute,
  AdminAdministratorEventsRoute: AdminAdministratorEventsRoute,
  AdminAdministratorPrayerTimesRoute: AdminAdministratorPrayerTimesRoute,
  AdminAdministratorIndexRoute: AdminAdministratorIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicAnnouncementsRoute: typeof PublicAnnouncementsRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicMonthlyTimetableRoute: typeof PublicMonthlyTimetableRoute
  PublicPrayerTimesRoute: typeof PublicPrayerTimesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAnnouncementsRoute: PublicAnnouncementsRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicMonthlyTimetableRoute: PublicMonthlyTimetableRoute,
  PublicPrayerTimesRoute: PublicPrayerTimesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
